# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssc-sensor-pressure.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ssc-sensor-pressure.proto\"9\n\x13SscPressureResponse\x12\x10\n\x08pressure\x18\x01 \x03(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssc_sensor_pressure_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SSCPRESSURERESPONSE._serialized_start=29
  _SSCPRESSURERESPONSE._serialized_end=86
# @@protoc_insertion_point(module_scope)
