# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssc-sensor-calories.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ssc-sensor-calories.proto\"\'\n\x13SscCaloriesResponse\x12\x10\n\x08\x63\x61lories\x18\x01 \x02(\x02\"4\n\x12SscCaloriesRequest\x12\x0e\n\x06period\x18\x01 \x01(\r\x12\x0e\n\x06vo2max\x18\x02 \x01(\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssc_sensor_calories_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SSCCALORIESRESPONSE._serialized_start=29
  _SSCCALORIESRESPONSE._serialized_end=68
  _SSCCALORIESREQUEST._serialized_start=70
  _SSCCALORIESREQUEST._serialized_end=122
# @@protoc_insertion_point(module_scope)
