# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssc-sensor-heart-rate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bssc-sensor-heart-rate.proto\"5\n\x14SscHeartRateResponse\x12\x0b\n\x03\x62pm\x18\x01 \x03(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssc_sensor_heart_rate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SSCHEARTRATERESPONSE._serialized_start=31
  _SSCHEARTRATERESPONSE._serialized_end=84
# @@protoc_insertion_point(module_scope)
